<?php 

$title = 'Delete album';
$this->headtitle($title);
?>
<h1><?php echo $this->escapehtml($title); ?></h1>

<p>Are you sure that you want to dlete
	'<?php echo $this->escapehtml($album->title); ?>' by
	'<?php echo $this->escapehtml($album->artist); ?>'?
</p>
<?php 
$url = $this->url('album', array(
	'action' => 'delete',
	'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
	<input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
</div>
</form>