<?php
$title = 'Edit album';
$this->headtitle($title);
?>
<h1><?php echo $this->escapehtml($title); ?></h1>
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'edit', 'id' => $this->id,)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formhidden($form->get('id'));
echo $this->formrow($form->get('title'));
echo $this->formrow($form->get('artist'));
echo $this->formsubmit($form->get('submit'));
echo $this->form()->closeTag();

?>
